name: flutter_pet_adoption_ui
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  
  animated_login: ^1.7.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/fonts/
   - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
